# --------------------------------------------------
# Site Settings
# --------------------------------------------------

# Menu
menu:
  home: / || é¦–é¡µ
  # galleries: /galleries/ || æ‘„å½±
  # archives: /archives/ || å½’æ¡£
  tags: /tags/ || æ ‡ç­¾
  categories: /categories/ || åˆ†ç±»
  # about: /about/ || å…³äº

# Color
color:
  text: '#88ada6'
  text-secondary: '#4e4e4e'
  text-third: '#999999'
  background: '#ffffff'
  background-secondary: '#f6f8fa'
  border: '#eeeeee'
  text-dark: '#dddddd'
  text-secondary-dark: '#9899ab'
  text-third-dark: '#7d8594'
  background-dark: '#1e2128'
  background-secondary-dark: '#1a1d22'
  border-dark: '#2b3038'
  link: '#FF3B00'
  link-gradient: 'linear-gradient(-60deg, #ff5858 0%, #f09819 100%)'
  link-hover: 'none'

# Favicon
favicon:
  small: /images/icons/dog.png
  medium: /images/icons/dog.png
  apple_touch_icon: /images/icons/dog.png
  safari_pinned_tab: /images/icons/dog.svg
  msapplication: /images/icons/dog.png

# Font
font:
  size: 17px
  family: 'Microsoft YaHei'

# Background Image
background_image:

# Loading
loading:
  gif: /images/theme/loading.gif
  lottie:

# Preview
preview:
  enable: true
  type: wave  # wave | cloud
  background:
    type: image # image video
    default_image:
      light: /images/theme/light.jpg
      dark: /images/theme/dark.jpg
    video:
    api:  # https://source.unsplash.com/random/1920x1080
    size: cover # css: background-size
    position: center # css: background-position
  motto:
    default: åŠ±å¿—æˆä¸ºæŠ€æœ¯å¤§ç‰›çš„ä¸€åå°ç™½
    color: '#ffffff'
    typing: true
    api: # https://v1.hitokoto.cn/?c=b
    data_contents: ['data', 'content']
    # ex.one  =>  apl: https://v1.hitokoto.cn/?encode=text&c=i  data_contents:
    # ex.two  =>  api: https://v2.jinrishici.com/one.json  data_contents: ['data', 'content']

# Navbar
navbar:
  enable: true
  back_home: true

# Copyright
copyright: <p>CopyrightÂ© 2023 å»ºç«™  |  ZcZjy ( è¿˜æ²¡å¤‡æ¡ˆå–”~ï¼ï¼ï¼ )</p><p>è”ç³»æˆ‘ï¼š540507521@qq.com</p><p>å…³äºæˆ‘ï¼šæˆ‘æ˜¯ZcZjy</p><p>ç§¯å°‘æˆå¤šï¼Œåªè¦å­¦ä¸æ­»å°±å¾€æ­»é‡Œå­¦ğŸ‘€</p><p>å–œæ¬¢åˆ†äº«ï¼Œä¹Ÿå–œæ¬¢äº¤æœ‹å‹ï¼Œæ­£åœ¨åŠªåŠ›é’»ç ”javaã€springå…¨å®¶æ¡¶ã€å‰ç«¯vueç­‰ç­‰æŠ€æœ¯ï¼Œæ¢¦æƒ³æˆä¸ºä¸€åæŠ€æœ¯å¤§ç‰›</p>

# Social
social:
  qq: tencent://message/?Menu=yes&uin=540507521 || iconQQ || '#12B7F5'
  wechat: javascript:; || iconwechat-fill || '#09BB07'
  # instagram: https://www.instagram.com/izhaoo/ || iconinstagram || '#DA2E76'
  github: https://github.com/Zc-Zjy || icongithub-fill || '#9f7be1'
  email: mailto:540507521@qq.com || iconmail

# Override Scrollbar
scrollbar:
  type: default # default | simple | normal | none

# Fab (Float Action Button)
fab:
  enable: true
  always_show: false

# Search
search:
  enable: true
  path: http://localhost:4000/search.xml  # ç´¢å¼•ç”Ÿæˆè·¯å¾„ï¼ˆéœ€è¦è®¾ç½®ç»å¯¹è·¯å¾„ï¼Œå¦åˆ™äºŒçº§é¡µé¢è¯»ä¸åˆ°ï¼‰
  field: post  # post page all
  format: html  # åªæ”¯æŒ html ç±»å‹
  content: true  # æ˜¯å¦åŒ…å«æ­£æ–‡å†…å®¹

# QR Code
qrcode:
  enable: false
  type: url # url | image
  image: https://pic.izhaoo.com/weapp-code.jpg

# Color Mode
color_mode:
  enable: true

# Gray (Mourning Mode)
gray:
  enable: false

# --------------------------------------------------
# Post Settings
# --------------------------------------------------

# Excerpt
excerpt:
  enable: true

# Post Image
post_image:
  random: local # local galleries
  default: /images/text_cover_background/cover_background_light.jpg

# Page Size
post_page_size:
  width: 1000px

# Caption
caption:
  enable: true

# Indent
indent:
  content:
  excerpt:

# TOC
toc:
  enable: true
  always_show: true
  min_depth: 1
  max_depth: 6

# Donate
donate:
  enable: true
  alipay: /images/zjyzfb.jpg
  wechat: /images/zjyzanshang.jpg

# Copyright
post_copyright:
  enable: true

# Carrierï¼ˆcopy article with one clickï¼‰
carrier:
  enable: true
  type: markdown # html | markdown | text

# --------------------------------------------------
# Page Settings
# --------------------------------------------------

# Galleries
galleries:
  enable: true
  title: æ‘„å½±
  subtitle: Photography
  type: waterfall # waterfall | grid
  columns: 3


# --------------------------------------------------
# Comment Settings
# --------------------------------------------------

comments:
  enable: true
  type: valine # gitalk | valine | changyan
  button: true

# Gitalk
gitalk:
  owner:
  repo:
  admin:
  clientID:
  clientSecret:

# Valine
valine:
  appId: YBz2laX5qgCJLxNTpC7akJuU-gzGzoHsz
  appKey: lHPh4E9b3LU0DWfqppMWL7Tt
  placeholder: O(âˆ©_âˆ©)O~æ¬¢è¿ç•™è¨€~vğŸ˜ï¼
  avatar: wavatar
  pageSize: 10
  lang: zh-CN

# ChangYan
changyan:
  appId:
  conf:

# --------------------------------------------------
# Plugin settings
# --------------------------------------------------

# Notification
notification:
  enable: false
  delay: 4500
  page_white_list:
  page_black_list:

# Daovoice
daovoice:
  enable: false
  appId: # app_id

# Tencent Chao
tencentChao:
  enable: false
  appId: # app_id

# LeanCloud
leancloud:
  enable: true
  appId: YBz2laX5qgCJLxNTpC7akJuU-gzGzoHsz
  appKey: lHPh4E9b3LU0DWfqppMWL7Tt
  serverURLs: https://leancloud.cn/

# Lazyload
lazyload:
  enable: true
  only_post: false
  loading:
    gif: /images/theme/loading.gif
    lottie:

# FancyBox
fancybox: true

# Pjax
pjax: false

# HighLight
highlight:
  enable: true
  style: # https://highlightjs.org/static/demo/
    light: Xcode
    dark: Solarized Dark

# SEO
seo:
  baidu_auto_push: true

# Analytics
analytics:
  baidu: 19f90ef28fbbe31a9902cc112b7dacce
  google: # id
  cnzz: # id

# --------------------------------------------------
# Script Settings
# --------------------------------------------------

# CDN
vendors:
  jquery_js: https://code.jquery.com/jquery-3.6.0.min.js
  fancybox_js: https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js
  pjax_js: https://cdn.bootcss.com/jquery.pjax/2.0.1/jquery.pjax.min.js
  lazyload_js: https://cdn.bootcdn.net/ajax/libs/jquery.lazyload/1.9.1/jquery.lazyload.min.js
  qrcode_js: https://cdn.bootcdn.net/ajax/libs/jquery.qrcode/1.0/jquery.qrcode.min.js
  daovoice_js: https://widget.daovoice.io/widget/0f81ff2f.js
  lottie_js: https://cdn.bootcdn.net/ajax/libs/lottie-web/5.7.12/lottie.js
  fancybox_css: https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.css
  highlight_css: https://cdn.bootcss.com/highlight.js/9.18.1/styles/
  iconfont_css: https://at.alicdn.com/t/font_1445822_p6ry5n7lrr.css

# Custom
custom:
  head: <script>var _hmt = _hmt || [];(function() {var hm = document.createElement("script");hm.src = "https://hm.baidu.com/hm.js?19f90ef28fbbe31a9902cc112b7dacce";var s = document.getElementsByTagName("script")[0]; s.parentNode.insertBefore(hm, s);})();</script>
  foot:
  css:
  js:
